### ISSUE TITLE
Finite pixel density

### ISSUE THREAD

**Issue by dmitrizzle** [SergioCrisostomo/Mootools-chart-flot#20]
I hope I'm posting in the right section. First off, thank you guys so much for developing this tool. It's brilliant!

Now the issue I'm having is with Retina displays that as you know requires either indefinite pixel density (as in vector graphics) or 2x pixels. With images it's typically not a problem, however with things like line graphs it's very noticeable. At least to a designer's eye.

See the attached image: compare the "sharpess" between the text and the lines drawn: the fonts seem to render perfectly, however the lines are "blurry" (you might need to zoom-in).

<img width="275" alt="screen shot 2016-01-23 at 11 23 14 am" src="https://cloud.githubusercontent.com/assets/8587882/12528306/d772b764-c1c3-11e5-8a14-f7af1a2e2a1b.png">

**Comment by SergioCrisostomo** [comment]
Hi @dmitrizzle, good point you bring up!

I found a simple solution by scaling the canvas. 
Do you mind to try it? => http://jsfiddle.net/0xjb1zn9/


If it solves the problem I will add it to the repo.


Cheers

**Comment by dmitrizzle** [comment]
Yes it works, thank you!

**Comment by SergioCrisostomo** [comment]
Fixed by 6879d95892aae63b13cb4b8408e696ca6a02ace0

Thank you again @dmitrizzle for pointing this out.

**Comment by dmitrizzle** [comment]
My pleasure. Thank you for developing MooTools Flot and gifting it to the dev community!

Is there a place to submit a feature request?

**Comment by SergioCrisostomo** [comment]
@dmitrizzle you can open a issue to add feature requests. If you have the code for it you are welcome to send a pull request directly :)

cheers

**Comment by dmitrizzle** [comment]
Will do :)
