### ISSUE TITLE
Bad helper function

### ISSUE THREAD

**Issue by Enyby** [SergioCrisostomo/Mootools-chart-flot#22]
at https://github.com/SergioCrisostomo/Mootools-chart-flot/blob/master/Source/moo.flot.js#L2424

```
            function controlArray(itm){
                if (eventname === 'plotclick'){

                    // get nearest point to clicked item using canvasX, canvasY
                    var positionArray = []; // [ y pos, array index ]
                    for(var m = 0; m < itm.length; m++){
                        positionArray.push([Math.abs(canvasY -itm[m].pageY), m]);
                    }
                    positionArray = positionArray.sort(function(a, b) {
                        return a[0] - b[0];
                    });
                    return itm[positionArray[0][1]];
                }
                if(itm.length) return itm;
                return null;
            }
```

must be

```
              function controlArray(itm){
                if (itm.length == 0) return null;
                if (eventname === 'plotclick'){

                    // get nearest point to clicked item using canvasX, canvasY
                    var positionArray = []; // [ y pos, array index ]
                    for(var m = 0; m < itm.length; m++){
                        positionArray.push([Math.abs(canvasY -itm[m].pageY), m]);
                    }
                    positionArray = positionArray.sort(function(a, b) {
                        return a[0] - b[0];
                    });
                    return itm[positionArray[0][1]];
                }
                return itm;
            }
```

Because if called 'plotclick' with empty array we try return unexsist index on line with:
`return itm[positionArray[0][1]];`
But if we add check on start it can not happens.

**Comment by SergioCrisostomo** [comment]
@Enyby good point. Will you send a pull request to fix that? We could also [refactor that to use `.map`](https://github.com/SergioCrisostomo/Mootools-chart-flot/commit/fa0d2df9b33b875aa197748631fe41d486446228) maybe more semantic.

**Comment by Enyby** [comment]
No. I do not send any pull request to any place.

**Comment by SergioCrisostomo** [comment]
@Enyby fixed the code. Thank you for the input again!

(PS. why don't you send pull request to any place? It makes maintaining useful tools easier)

**Comment by Enyby** [comment]
I do not quite understand what you want from me. These make a request or in the flot. If here, then it's easier to do yourself. If, however, flot, there is very different code. There are many changes that are not reflected here.

**Comment by SergioCrisostomo** [comment]
@Enyby so to be more clear: Thank you for pointing these bugs, I corrected them with your help.

In the future if you find errors or improvements in someone else's code you can send a pull request and they just have to press a button to have it included. Often the person finding the fix has good understanding of the problem and can describe it and find solution better. To receive a "ready" pull request is worth gold :)

Anyway, thank you for suggesting fixes to those lines! If you find more let me know! 

I am dreaming with making a JS Codeshift from jQuery to MooTools and we could import a lot of stuff with it :) Somewhere in the future...

**Comment by Enyby** [comment]
Too many actions for create pull request. I need fork project to my github account, change code, only after that I can post pull request. I do not want fork every project when I found bug in it.

```
You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork Enyby/Mootools-chart-flot, so you can send a pull request. 
```

**Comment by SergioCrisostomo** [comment]
@Enyby  I understand. I am happy also if you "only" report bugs you found. That is really nice!

Take care!
